In [1]:
import numpy as np

In [2]:
e = np.full((2,2),7)

In [3]:
e

array([[7, 7],
       [7, 7]])

In [4]:
d = np.arange(10,25,5)

In [5]:
d

array([10, 15, 20])

In [6]:
f = np.linspace(0,2,9)

In [7]:
f


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
g = np.eye(2)

In [9]:
g

array([[1., 0.],
       [0., 1.]])

In [10]:
h = np.random.random((2,2))

In [11]:
h

array([[0.66269766, 0.83931862],
       [0.74923477, 0.3658209 ]])

In [12]:
d = np.empty((3,2))  

In [13]:
d

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.save('my_array',d)

In [16]:
np.savez('array.npz',h,d)

In [18]:
np.load('my_array.npy')

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
x = np.load('array.npz')

In [21]:
x

In [22]:
#saving and loading text files

In [30]:
np.savetxt('myarray.txt',h,delimiter=" ")

In [38]:
np.savetxt('myarray.csv',h,delimiter=" ")

In [39]:
np.loadtxt("myarray.txt")

array([[0.66269766, 0.83931862],
       [0.74923477, 0.3658209 ]])

In [40]:
np.loadtxt("myarray.txt",dtype=int)

array([[0, 0],
       [0, 0]])

In [42]:
np.genfromtxt("myarray.csv",delimiter=" ")

array([[0.66269766, 0.83931862],
       [0.74923477, 0.3658209 ]])

In [47]:
a = np.arange(6).reshape(3,2)
a.shape
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [46]:
len(a)

3

In [48]:
a.ndim

2

In [49]:
a.size

6

In [50]:
a.dtype

dtype('int32')

In [51]:
a.dtype.name

'int32'

In [53]:
h.astype(int)

array([[0, 0],
       [0, 0]])

In [54]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [56]:
#array arithmetic

In [61]:
a = np.arange(2,13,2).reshape(3,2)

In [62]:
a

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [63]:
b = np.arange(6,17,2).reshape(3,2)

In [64]:
b

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [65]:
g = b-a

In [66]:
g

array([[4, 4],
       [4, 4],
       [4, 4]])

In [68]:
np.subtract(b,a)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [74]:
v=np.add(b,a)
v

array([[ 8, 12],
       [16, 20],
       [24, 28]])

In [75]:
h = a+v

In [76]:
h

array([[10, 16],
       [22, 28],
       [34, 40]])

In [79]:
np.divide(b,a)

array([[3.        , 2.        ],
       [1.66666667, 1.5       ],
       [1.4       , 1.33333333]])

In [80]:
np.multiply(a,b)

array([[ 12,  32],
       [ 60,  96],
       [140, 192]])

In [81]:
a

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [82]:
b

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [84]:
np.exp(b)

array([[4.03428793e+02, 2.98095799e+03],
       [2.20264658e+04, 1.62754791e+05],
       [1.20260428e+06, 8.88611052e+06]])

In [85]:
np.sqrt(b)

array([[2.44948974, 2.82842712],
       [3.16227766, 3.46410162],
       [3.74165739, 4.        ]])

In [86]:
np.sin(a)

array([[ 0.90929743, -0.7568025 ],
       [-0.2794155 ,  0.98935825],
       [-0.54402111, -0.53657292]])

In [87]:
np.cos(b)

array([[ 0.96017029, -0.14550003],
       [-0.83907153,  0.84385396],
       [ 0.13673722, -0.95765948]])

In [91]:
np.log(b)

array([[1.79175947, 2.07944154],
       [2.30258509, 2.48490665],
       [2.63905733, 2.77258872]])

In [94]:
a

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [100]:
c = np.arange(6).reshape(2,3)

In [101]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [102]:
a.dot(c)

array([[12, 18, 24],
       [24, 38, 52],
       [36, 58, 80]])

In [103]:
a == b

array([[False, False],
       [False, False],
       [False, False]])

In [104]:
a<b

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [105]:
np.array_equal(a,b)

False

In [106]:
#Aggregate Function

In [107]:
a.sum()

42

In [108]:
b.sum()

66

In [110]:
a.min()

2

In [111]:
b.max(axis=0)

array([14, 16])

In [113]:
b.max(axis=1)

array([ 8, 12, 16])

In [114]:
b.cumsum(axis=1)

array([[ 6, 14],
       [10, 22],
       [14, 30]], dtype=int32)

In [115]:
b

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [119]:
a.mean()

7.0

In [125]:
np.std(a)

3.415650255319866

In [126]:
a

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [127]:
h=a.view()

In [128]:
h

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [131]:
z=np.copy(a)

In [132]:
z

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [133]:
h=a.copy()

In [134]:
h

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [141]:
h.sort()

In [142]:
h

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [145]:
a.sort(axis=0)

In [146]:
a

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [147]:
#subsetting:


In [148]:
a = np.array([1,2,3])

In [149]:
a

array([1, 2, 3])

In [150]:
a[2]

3

In [152]:
b = np.array([[1,2,3],[4,5,6]])

In [153]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [154]:
b[1,2]

6

In [156]:
b[0,2]

3

In [159]:
a[0:2]

array([1, 2])

In [167]:
b[0:2,1]

array([2, 5])

In [168]:
b[:1]

array([[1, 2, 3]])

In [170]:
b[1]

array([4, 5, 6])

In [171]:
b[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [175]:
b[b<4]

array([1, 2, 3])